name: ${parent.artifactId}-${artifactId}
version: ${version}
main: dev.cerus.mapads.discordbot.plugin.MapAdsDiscordPlugin
author: Cerus
api-version: 1.16

libraries:
  - "org.xerial:sqlite-jdbc:3.36.0.3"